title = "Seshan's Personal Website"
header = "Seshan Ravikumar"
subheader = "<strong>aka. Seshpenguin<img src=\"/public/paimon.png\" style=\"display: inline; height: 2em; margin-bottom:  -7px; margin-left: 4px;\" /></strong>"
desc = "aka. Seshpenguin. This is my personal website, and is the official source for my verified accounts online."
copyright = "Seshan Ravikumar"