title = "Seshan's Personal Website"
header = "Seshan Ravikumar"
subheader = "<strong>aka. Seshpenguin<img src=\"/public/paimon.png\" style=\"display: inline; height: 2em; margin-bottom:  -7px; margin-left: 4px;\" /></strong>"
copyright = "Seshan Ravikumar"